# 此文件用于提供哨兵左侧 MID360 Point-LIO 的默认 ROS2 参数。
/**:
  ros__parameters:
    odom_only: false
    odom_header_frame_id: odom
    odom_child_frame_id: base_link
    prop_at_freq_of_imu: true
    use_imu_as_input: true
    check_satu: true
    init_map_size: 100
    point_filter_num: 2
    filter_size_surf: 0.5
    filter_size_map: 0.5
    cube_side_length: 200.0
    space_down_sample: true
    runtime_pos_log_enable: false
    common:
      lid_topic: /livox/lidar_192_168_1_3
      imu_topic: /livox/imu_192_168_1_3
      con_frame: false
      con_frame_num: 1
      cut_frame: false
      cut_frame_time_interval: 0.1
      time_lag_imu_to_lidar: 0.0
    communication:
      lidar_qos_depth: 5
      imu_qos_depth: 0
      imu_buffer_seconds: 3.0
      imu_expected_frequency_hz: 200.0
    preprocess:
      lidar_type: 1
      scan_line: 4
      scan_rate: 10
      timestamp_unit: 3
      blind: 0.5
    mapping:
      imu_en: true
      start_in_aggressive_motion: false
      extrinsic_est_en: false
      imu_time_inte: 0.005
      satu_acc: 3.0
      satu_gyro: 35.0
      acc_norm: 1.0
      lidar_meas_cov: 0.01
      acc_cov_output: 500.0
      gyr_cov_output: 1000.0
      b_acc_cov: 0.0001
      b_gyr_cov: 0.0001
      imu_meas_acc_cov: 0.01
      imu_meas_omg_cov: 0.01
      gyr_cov_input: 0.01
      acc_cov_input: 0.1
      plane_thr: 0.1
      match_s: 81.0
      fov_degree: 180.0
      det_range: 100.0
      gravity_align: true
