#!/usr/bin/env python3
"""Generate the lidar probe from the stage-one assets without altering them."""
from pathlib import Path
import xml.etree.ElementTree as ET

# Build a sensor-equipped derivative; all scan coordinates are relative to z=0.7.
def generate_probe():
    """Write probe world/model and exact external frame for the real Gazebo sensor."""
    package = Path(__file__).resolve().parents[1]
    model = ET.parse(package/'models/sentry/model.sdf')
    link = model.getroot().find('model/link')
    link.append(ET.fromstring("""<sensor name="lidar_sensor" type="gpu_lidar">
      <pose>0 0 0.7 0 0 0</pose><topic>/sentry/lidar</topic>
      <update_rate>5</update_rate><always_on>true</always_on><visualize>false</visualize>
      <lidar><scan><horizontal><samples>360</samples><resolution>1</resolution>
      <min_angle>-3.141592653589793</min_angle><max_angle>3.141592653589793</max_angle></horizontal>
      <vertical><samples>4</samples><resolution>1</resolution><min_angle>-0.1</min_angle><max_angle>0.1</max_angle></vertical></scan>
      <range><min>0.2</min><max>10</max><resolution>0.01</resolution></range></lidar>
    </sensor>"""))
    folder=package/'models/sentry_lidar';folder.mkdir(exist_ok=True)
    model.getroot().insert(0,ET.Comment('Generated by lidar_assets.py: stage-one model with a real 360x4, 5 Hz lidar.'))
    ET.indent(model);model.write(folder/'model.sdf',encoding='unicode',xml_declaration=True)
    (folder/'model.config').write_text('<?xml version="1.0"?>\n<!-- Sensor-equipped ideal navigation model. -->\n<model><name>sentry_lidar</name><version>1.0</version><sdf version="1.8">model.sdf</sdf></model>\n')
    world=ET.parse(package/'worlds/basic.sdf');w=world.getroot().find('world')
    w.set('name','sentry_probe')
    w.find('include/uri').text='model://sentry_lidar'
    w.append(ET.fromstring('<plugin filename="ignition-gazebo-sensors-system" name="ignition::gazebo::systems::Sensors"><render_engine>ogre2</render_engine></plugin>'))
    # A known wall at x=3 tests actual range, independently of the map asset.
    w.append(ET.fromstring('<model name="calibration_wall"><static>true</static><pose>3.05 0 0.75 0 0 0</pose><link name="wall"><visual name="wall"><geometry><box><size>0.1 4 1.5</size></box></geometry><material><ambient>0.9 0.4 0.1 1</ambient><diffuse>0.9 0.4 0.1 1</diffuse></material></visual></link></model>'))
    world.getroot().insert(0,ET.Comment('Generated by lidar_assets.py: sensor feasibility world and known x=3 m wall.'))
    ET.indent(world);world.write(package/'worlds/lidar_probe.sdf',encoding='unicode',xml_declaration=True)

if __name__=='__main__':
    generate_probe()
